### PR TITLE
store sandbox using yui-sandbox

### PR DESCRIPTION
**Pull request by caridy**
- isolation between store instance and the mojito Y instace
- remove experimental dataprocess

### CODE REVIEW

**Comment by mojit0** [comment]
+1

**Comment by caridy** [comment]
let's wait until after pr2 patch happens to merge this.

**Comment by caridy** [comment]
Travis is failing due to a timeout rather than a code problem I guess: "Executing your script (./travis/script.sh) took longer than 30 minutes and was terminated."

**Comment by drewfish** [comment]
+1.  I think that store.server.js should probably be using yui-sandbox instead, for when it uses Y.Loader.

**Comment by caridy** [comment]
Yes, part of the next refactor. Trello card #88 :)

**Pull request merged**
