### PR TITLE
Pull request for feature request: https://github.com/yahoo/mojito/issues/208

### PR DESCRIPTION
**Pull request by imalberto**
Changes with unit tests:
- source/lib/app/addons/ac/output-adapter.common.js
- source/lib/app/addons/view-engines/mu.server.js
- source/lib/app/autoload/view-renderer.common.js
- source/lib/tests/autoload/app/addons/view-engines/mu-tests.server.js 

Feedback welcome.

### CODE REVIEW

**Comment by rwaldura** [comment]
This fix is for issue 208.

**Comment by rwaldura** [comment]
This fix is for GitHub issue #208

**Comment by rwaldura** [comment]
See also related pull request #179 which is about Handlebar support.

**Comment by rwaldura** [comment]
this is required for BPi support

**Comment by imalberto** [comment]
This pull request has been superceded by : https://github.com/yahoo/mojito/pull/371

**Pull request closed without merging**
