### PR TITLE
FIX: mojit achetypes; added ejs to devDependencies;

### PR DESCRIPTION
**Pull request by imalberto**

### CODE REVIEW

**Comment by caridy** [comment]
+1

**Comment by mridgway** [comment]
What is ejs being used for?

**Comment by imalberto** [comment]
"ejs" is being used by some of the developerguide examples showcasing templates.

**Comment by isao** [comment]
@imalberto can we remove ejs and the associated test that requires it? ejs is not whitelisted for internal use per @caridy

**Comment by imalberto** [comment]
OK. Just sync'ed with @caridy. Removed in commit https://github.com/imalberto/mojito/commit/3c2c36d03550a0ad701349894e0e78e4db59ec23 as part of PR #682

**Pull request merged**
