### PR TITLE
fixing regression in mojito@0.5.5 that breaks shaker

### PR DESCRIPTION
**Pull request by caridy**

### CODE REVIEW

**Comment by rwaldura** [comment]
Is this the final fix, that yields a new Shaker release?
Either way, you’re awesome.

**Comment by drewfish** [comment]
+1

**Comment by rwaldura** [comment]
I want to use this issue to keep track of all issues related to this compatibility break.
E.g. see also yahoo/mojito-shaker#43

**Comment by caridy** [comment]
@rwaldura this is the only change for the patch. Once we get confirmation from Albert, we can issue the patch or just 0.5.6, whatever works best.

As a side note, this is not related to yahoo/mojito-shaker#43, it was a bug I introduced as part of PR #997

**Pull request merged**
