### PR TITLE
Fix buffer mojito040

### PR DESCRIPTION
**Pull request by imalberto**
This pull request supercedes https://github.com/yahoo/mojito/pull/209 to merge with develop. Original pull request is outdated.

### CODE REVIEW

**Comment by mridgway** [comment]
Hi Alberto, we recently added the Handlebars view engine. Do the changes to the mu engine need to be applied there as well? I can't tell whether the Handlebars engine would need any changing to support this.

**Comment by mridgway** [comment]
Looks good to me. :shipit:

**Comment by rwaldura** [comment]
Supersedes PR #209.

**Comment by drewfish** [comment]
+1

**Comment by mridgway** [comment]
So the options are now passed to the mustache engine but not the Handlebars. So we need to decide whether options should be passed to Handlebars or the options go away once we remove Mustache.

**Comment by drewfish** [comment]
I like this feature, since it allows users to customize how the view engines run.  So I propose we pass the options to Handlebars.

**Comment by caridy** [comment]
:+1: it will not hurt to have that in place in case someone wants to hack into the _template_ engine.

**Pull request merged**
