### PR TITLE
add node 0.8 compatibility 

### PR DESCRIPTION
**Pull request by isao**
test for node 0.8's fs.existsSync() or older path.existsSync() and
use the appropriate one. (async form not used in mojito). 

mojito test passes on node vers 0.8.6 and 0.6.19

### CODE REVIEW

**Comment by rwaldura** [comment]
does this PR supersede #250?

**Comment by isao** [comment]
@rwaldura yes, that pr couldn't merge automatically, and assumed `var path` etc where mojito code used `var pathlib`, var `libfs` etc... Also didn't incl 0.6 support

**Comment by isao** [comment]
updated to be merge-able, omitting the dep version edits

**Comment by mridgway** [comment]
:shipit:

**Pull request merged**
