### PR TITLE
Fix a bug on mustache that prevents page rendering (crashes) when binding data contains null

### PR DESCRIPTION
**Pull request by macmacbr**
Fix a bug on mustache that prevents page rendering (crashes) when binding data contains null.

### CODE REVIEW

**Comment by drewfish** [comment]
I think we have a preference to update the mustache library outright, pull request #116, rather than try to patch an old version.

**Comment by mridgway** [comment]
Unfortunately even the latest version of the Mu library doesn't fix this issue either. I think the Mu library needs to be replaced, as it doesn't seem up to par with the Mustache spec. Dot notation doesn't work with Mu either.

**Comment by isao** [comment]
Thanks Marco, I cleaned up the pull request a bit and resubmitted it for you. pull #207

closing this one.

**Comment by rwaldura** [comment]
Yeah, we're ditching Mu in favor of Handlebars -- see pull request #179.

**Comment by isao** [comment]
Yup can't wait for pull #179 too. As-is the handlebars pull is opt-in, so this bug fix is nice until the internal mu renderer goes away.

**Comment by rwaldura** [comment]
Unfortunately we're having to delay Handlebar support, so we're going to pull in request #211 which fixes the NULL case.

**Pull request closed without merging**
