### PR TITLE
Update docs/dev_guide/intro/mojito_apps.rst

### PR DESCRIPTION
**Pull request by nonopolarity**
files that are not created by default

### CODE REVIEW

**Comment by zhouyaoji** [comment]
Thanks, jianlin! Could I ask you to make a couple of changes to your pull request?

I would like to remove the space between the text and the asterisk. 

For example, could you make the following changes:  
- ``addons`` \* => ``addons``\\* 
- ``default.json`` \*  => ``default.json``\*

Thanks, again.

**Comment by nonopolarity** [comment]
I did another commit.  Would you like to give it a try?

**Comment by zhouyaoji** [comment]
Thanks, jianlin, but, unfortunately, you have to escape the asterisk because it's adjoining the syntax for notating monospace text. Thus, ``addons``_' will  render *_incorrectly*_, but ``addons``\_' will render correctly. I tried to make that clear in the example I gave you, but GH removed the escape symbol "\".

So, if you look at the rendered page from your changes at https://github.com/jianlin/mojito/blob/4fb37c29483059f7703b4dcc28420de759717852/docs/dev_guide/intro/mojito_apps.rst, you will see that the backticks are displayed.

Sorry to ask you to make another change!

**Comment by zhouyaoji** [comment]
Hi jianlin,

I made the change myself and added 'routes.json' to the list as well as added an asterisk to 'yui_modules', which isn't created by default either. I'll go ahead and close your pull request. Thanks again!

**Pull request closed without merging**
