### PR TITLE
modify dimensions.json to meet ycb standard

### PR DESCRIPTION
**Pull request by lzhan**

### CODE REVIEW

**Comment by caridy** [comment]
@lzhan those environments are not aligned with those defined in the manhattan workflow. Is that something we want to provide out of the box as the default config or not?

**Comment by lzhan** [comment]
@caridy Thanks for point it out. I am trying to fix bug 5532859 which requires our default dimensions.json to meet an ycb doc. I am not aware of the "the manhattan workflow". Would you please give me a pointer?

**Comment by redonkulus** [comment]
@caridy seems like the manhattan workflow would be a specific yahoo use case right? Is that something we need to enforce for the non-y community?

**Comment by lzhan** [comment]
I am closing this pr and will send another pr with 1) keep current dimension.json for open source user. 2) An new dimension.json for yahoo internal user-- when internal user create mojito app, the dimension.json for internal user will be used.

**Pull request closed without merging**
