### PR TITLE
Moved yuitest and jslint to devDependencies

### PR DESCRIPTION
**Pull request by mridgway**
If this is approved, go ahead and merge.

### CODE REVIEW

**Comment by isao** [comment]
+1

**Comment by drewfish** [comment]
I mostly agree.  However, there is a user-training/documentation component (since users will need to install mojito with the `-dev` flag).

**Comment by mridgway** [comment]
This shouldn't actually change anything for the user. By default, `npm install` will also install devDependencies. In order to not install them, one would pass the production flag: `npm install --production`

**Comment by drewfish** [comment]
Ah, great.

+1

**Comment by isao** [comment]
@mridgway `npm i mojito` won't install mojito's devDependencies - that will require `cd path/to/mojito && npm i` at least for recent npms

**Comment by mridgway** [comment]
Yeah, I would argue that's a bug with npm.

**Pull request merged**
