### PR TITLE
Restructured docs to have a single TOC

### PR DESCRIPTION
**Pull request by rmadhuram**

### CODE REVIEW

**Comment by rwaldura** [comment]
@zhouyaoji any comments?

**Comment by zhouyaoji** [comment]
Sorry, I still want to review the changes. I am not sure why we are changing the title of the inter-mojit communication examples to "Allowing Inter-Mojit Communication". This does not follow the format for the other code example chapters. 

Basically, it's breaking the parallelism of the titles: 

Configuration

Views

Assets

Data Access

Events

Inter-Mojit Communication  (Allowing... -> this doesn't follow)

Other

**Comment by rmadhuram** [comment]
Hi Joe, actually it was originally titled "Allowing Inter-Mojit Communication". I changed it to "Inter-Mojit Communication". Green is mine, red is previous.

Thanks,
Raj

**Comment by zhouyaoji** [comment]
Okay, sorry. I was glancing at the changes. Thanks, that's what it should be.

**Comment by rwaldura** [comment]
thanks @rmadhuram you're our hero!

**Pull request merged**
