### PR TITLE
fix for issue546 - jslint errors in the code examples (getting-started-guide)

### PR DESCRIPTION
**Pull request by dmitris**
RE https://github.com/yahoo/mojito/issues/546

This pull requests fixes or at least sliences all the JSLint errors and warnings in examples/getting-started-guide.  The fixes for the developer-guide are stil TODO (https://github.com/dmitris/mojito/commit/d466d17e1d5e6cfa1cdd4f502782f2315aa9c53f is the first one)

### CODE REVIEW

**Comment by dmitris** [comment]
Let me know if this is right way to fix the jslint issues and worth to continue.

**Comment by drewfish** [comment]
Hi Dmitri,

This looks great!  We're already doing a lot of `/*jslint anon:true, sloppy:true, nomen:true, node:true*/` in other places in Mojito, so that approach is valid.  (If we change our mind about that, we'll have a lot of other things to change as well.)

One thing:  so far in Mojito we've been trying to honor `plusplus:false`, so that means changing the `for (...; ...; i++)` to `for (...; ...; i += 1)`.

**Comment by dmitris** [comment]
what about the idiom:

var x, y, z, i = 0;
for (; i < 10; i += 1) {}

I read that it is done to save a few bites (minification).  What should we change it to?  I did in several examples:

var x, y, z, i;
for (i = 0; i < 10; ...

is it right?

**Comment by caridy** [comment]
Can we close this? /cc @zhouyaoji @drewfish @lzhan

**Comment by drewfish** [comment]
The following examples have jslint errors:
- developer-guide/binding_events
- developer-guide/configure_routing
- developer-guide/device_views
- developer-guide/framed_assets
- developer-guide/framed_config
- developer-guide/generating_urls
- developer-guide/hello
- developer-guide/htmlframe_mojit
- developer-guide/inter-mojit
- developer-guide/locale_i18n
- developer-guide/model_yql
- developer-guide/multiple_mojits
- developer-guide/scroll_views
- developer-guide/simple_assets
- developer-guide/simple_config
- developer-guide/simple_logging
- developer-guide/simple_view
- developer-guide/using_cookies
- developer-guide/using_parameters
- getting-started-guide/part2/basic_yql
- getting-started-guide/part3/intl-templates
- getting-started-guide/part4/paged-yql
- getting-started-guide/part5/flickr-list
- input/cookies
- input/get
- input/merged
- input/post
- input/route
- performance/string
- sandbox/bindercomm
- sandbox/binderrender
- sandbox/bindertime
- sandbox/controller-state
- sandbox/lazy_load
- sandbox/metabubble
- sandbox/server_side
- sandbox/strangeloop
- sandbox/view_refresh
- sandbox/yuiconf
- simple/part3
- simple/part4
- simple/part5
- simple/part6
- simple/part7
- simple/part8

**Comment by caridy** [comment]
Can we close this PR? /ping @zhouyaoji @drewfish

**Comment by drewfish** [comment]
We still have a _lot_ of examples that are failing jslint.

**Pull request closed without merging**
