### PR TITLE
mojito yaf-develop to use the bleeding version of yui to keep them in sync

### PR DESCRIPTION
**Pull request by caridy**
trying to get travis to build yui npm module using after_install.

### CODE REVIEW

**Comment by drewfish** [comment]
Is this the approach that YUI uses for their travis builds?

**Comment by drewfish** [comment]
From the travis logs:  `make: *** No rule to make target 'npm'.  Stop.`

**Comment by caridy** [comment]
@drewfish yes, this is the approach they use. I had some issues with the path, and the workflow, should be solved with the last  commit.

**Comment by caridy** [comment]
@drewfish it seems to be working now. Can you try it locally, by running `./travis/travis.sh`?

Things that are pending:
- how to facilitate the use of this travis config for bleeding branches only but not on develop and master?
- how to speed up the process since it takes a long time now due the YUI builder?

**Comment by mridgway** [comment]
+1, looks good.

**Comment by drewfish** [comment]
I got this error:

```
shifter --config build-npm.json
make: shifter: No such file or directory
make: *** [npm] Error 1
```

**Comment by drewfish** [comment]
Also, after cloning the YUI repo into `yui-src`, it doesn't appear to checkout the `3.x` branch.

**Comment by caridy** [comment]
@drewfish I added the -b 3.x option on the clone command as part of #459

**Pull request merged**
