### PR TITLE
rename TunnelClient to TunnelCommon everywhere

### PR DESCRIPTION
**Pull request by drewfish**
Also fixed the RPC to server.

### CODE REVIEW

**Comment by isao** [comment]
+1

**Comment by caridy** [comment]
I'm not so sure I like that name. In my mind, the tunnel is still a "client" in a sense that it is suppose to ack like a client to a remote mojito server.

**Comment by drewfish** [comment]
I see.  It's affinity is "common" however.

**Comment by drewfish** [comment]
I'll rename it to just "Tunnel".  (It -is- a client, as in "mysql client" or "http client", but "client" can get confused with our affinity:client.)

**Comment by drewfish** [comment]
I'll also add a note to the `delete command.rpc` that it might need to move to a different place in the future.

**Comment by drewfish** [comment]
Actually, TunnelClient does make more sense once I look at the context more.  Closing this, will issue a new PR with necessary other changes.

**Pull request closed without merging**
