### PR TITLE
Adding meta config field for HTMLFrameMojit to create meta tags

### PR DESCRIPTION
**Pull request by markandey**
Adding a config attribute meta for HTMLFrameMojit 
if application.json contains

<pre>        "specs": {
            "frame": {
                "type": "HTMLFrameMojit",
                "config": {
                    "title": "Hello App",
        ------->     "meta": [{
                        "name": "hello",
                        "content": "hi"
                    }],
         ...
</pre>

<pre>
&lt;!DOCTYPE HTML&gt;
&lt;html&gt;
&lt;head&gt;
&lt;script type=&quot;text/javascript&quot;&gt;var MOJITO_INIT=new Date().getTime();&lt;/script&gt;
&lt;meta &quot;name&quot;=&quot;hello&quot; &quot;content&quot;=&quot;hi&quot; &gt;

&lt;title&gt;Hello App&lt;/title&gt;
...
</pre>

### CODE REVIEW

**Comment by drewfish** [comment]
I actually prefer a different approach, where Mojito makes it easy for anyone to write their own replacement to HTMLFrameMojit.  (HTMLFrameMojit doesn't really do that much that is special.)  In Yahoo, we already have a couple of teams who've written their own custom versions.

**Comment by markandey** [comment]
It's your call..
Since HTMLFrameMojit is part of framework and documented, people will use it and then they might find it hard to add a meta tags. 
I saw the HTMLFrameMojit's **template(view)  was having a way to add**, but somehow it was not implemented in **Controller**. SO I thought this could be one of the TBD task.

**Comment by rwaldura** [comment]
See also issue #230.

**Comment by rwaldura** [comment]
As Drew mentioned, the current HTMLFrameMojit has some limitations, which Mojito users like yourselves run into rather quickly. 

We can patch the existing mojit, but it seems like a real chance for something new and better. Would you be interested in offering your own for adoption? 

@renatoi may have some comments here, re. e.g. the MicroFrame?

**Pull request closed without merging**
