### PR TITLE
Fix for expandinstace so we dont copy the params object

### PR DESCRIPTION
**Pull request by diervo**
Performance boost!

### CODE REVIEW

**Comment by drewfish** [comment]
This is missing `child.config` which is very important I suspect.

**Comment by diervo** [comment]
This is a Ric and I fix for avoid the overhead of copying the params. It seems that is working fine..
It was never there in the first place...

**Comment by diervo** [comment]
This is input to the composite addon, and in the docs seems that we dont need the config at all. It only mention params: 

```
cfg = {
    children: {
        slot-1: {
            type: "default",
            action: "index"
        },
        slot-2: {
            type: "default",
            action: "index",
            params: {
                route: {},
                url: {},
                body: {},
                file: {}
            }
        }
    },
    assets: {}
}
```

**Comment by drewfish** [comment]
I think `child.config` is needed by other users.

**Comment by diervo** [comment]
I just added the config to the PR :)

**Pull request merged**
