### PR TITLE
fixed YCB tests

### PR DESCRIPTION
**Pull request by drewfish**
The YCB tests were being skipped, and had been for a long time.  This PR both gets them running again, and updates them since they were quite old.

### CODE REVIEW

**Comment by isao** [comment]
did this pass secondary?

**Comment by drewfish** [comment]
Alas, I didn't try.

**Comment by isao** [comment]
secondary for pull job 25 has one failure

```
PreInitTest(com.yahoo.test.mojito.framework.usecase.BugVerificationTest): expected:<true> but was:<false>
```

**Comment by drewfish** [comment]
incorporated in PR #327.

**Pull request closed without merging**
