### PR TITLE
mojito-data-addon

### PR DESCRIPTION
**Pull request by caridy**
most of the changes proposed are in place, tests are missing, docs are missing, and a deep review is needed.

fixes [bz #6244112]

### CODE REVIEW

**Comment by drewfish** [comment]
Looks pretty good.  We should pay special attention to the results of the functional tests, because the are all we have for testing mojito client-side.

**Comment by drewfish** [comment]
I've fixed a couple of tests on https://github.com/drewfish/mojito/tree/data-channels, will work on more.

**Comment by caridy** [comment]
@drewfish unit tests are ok now! travis is not doing much on the functionals though!

**Comment by drewfish** [comment]
Yeah, I'm running functional tests by hand locally.  Lots of failures there, so I'll have more commits to fix those.

**Comment by caridy** [comment]
@drewfish merged the latest, now we have some unit tests failing:

13 Passed, 4 Failed , 0 skipped
 in composite tests
- test proxied mojits are processed properly:Unexpected error: Cannot read property 'proxied' of undefined
- test defered mojits are processed properly:Unexpected error: Cannot read property 'proxied' of undefined
- test addChild defer response:Unexpected error: Cannot read property 'proxied' of undefined
- test addChild proxy response:Unexpected error: Cannot read property 'proxied' of undefined

**Comment by drewfish** [comment]
Yeah, I saw those.  I'll circle back to fix those before finishing fixing the functional tests.

**Pull request merged**
