### PR TITLE
temporarily using mojito next as dependency

### PR DESCRIPTION
**Pull request by lzhan**

### CODE REVIEW

**Comment by caridy** [comment]
We should probably have a todo list in trello to avoid forgetting the fixes for all these little things.

**Comment by caridy** [comment]
travis issue:

```
node app.js
/home/travis/build/yahoo/mojito/examples/quickstartguide/app.js:18
app.use(mojito.middleware());
               ^
TypeError: Object function Mojito(app) {
    this._app = app;
    this._config = {};
    extend(Mojito, libdispatcher, liblogger, libmiddleware, libtunnel);
    app.mojito = {};
    this._init(app);
    return this;
} has no method 'middleware'
    at Object.<anonymous> (/home/travis/build/yahoo/mojito/examples/quickstartguide/app.js:18:16)
```

seems to be related.

**Comment by lzhan** [comment]
It is related. I am checking.

**Comment by isao** [comment]
@lzhan: discussed with @imalberto, and he is making a PR that installs just the node-markdown dependency in the quickstart guide example, so that it should behave like the other examples (no double-cloning)

**Comment by imalberto** [comment]
Closing this PR in favor of https://github.com/yahoo/mojito/pull/1205

**Pull request closed without merging**
