### PR TITLE
removing the ability to customize default middleware functions

### PR DESCRIPTION
**Pull request by caridy**
`libmojito.middleware()` will not longer take in consideration the `middleware` `array` defined in `application.json`, instead, developer will have to define their own middleware manually thru `app.use()`.

this is the result of the discussion in https://github.com/yahoo/mojito/issues/1320#issuecomment-35456242
## official docs:

By default, Mojito does not add its built-in middleware, in case the
application would like to need customization. Users have to explicity
request Mojito to add them.

``` js
    app.use(libmojito.middleware());
```

The most common usage is:

``` js
    var express = require('express'),
        libmojito = require('mojito'),
        app;

    app = express();
    libmojito.extend(app);
    app.use(libmojito.middleware());
```

But if you want to have more control over the middleware that you want
to put in place, you could dome something like this:

``` js
    var express = require('express'),
        libmojito = require('mojito'),
        app;

    app = express();
    libmojito.extend(app);
    app.use(myCustomMiddleware());
    app.use(libmojito.middleware['mojito-handler-static']());
    app.use(libmojito.middleware['mojito-parser-body']());
    app.use(libmojito.middleware['mojito-parser-cookies']());
    app.use(libmojito.middleware['mojito-contextualizer']());
    app.use(myCustomContextualizerMiddleware());
    app.use(libmojito.middleware['mojito-handler-tunnel']());
    app.use(anotherCustomMiddleware());
```
## TODO:
- [x] unit tests
- [x] func tests
- [x] docs

### CODE REVIEW

**Comment by imalberto** [comment]
LGTM, pending tests passing.
/cc @aljimenez @zhouyaoji

**Comment by caridy** [comment]
solves issue #1320

**Comment by drewfish** [comment]
One test is failing in travis.

**Comment by caridy** [comment]
yes, trying to figure out what's going on, there is a func test failing.

**Comment by caridy** [comment]
alright, all systems are green now!

**Comment by imalberto** [comment]
+1

**Pull request merged**
