### PR TITLE
adding routes in the readme file

### PR DESCRIPTION
**Pull request by selfcontained**
adding clarification surrounding routes in the readme file so developers are aware of it from their initial exposure to the library

### CODE REVIEW

**Comment by rwaldura** [comment]
Thanks for the patch bmharris. 
Is it better to mention routes right upfront, in the README, or should we attempt to delay that complexity till later -- and use a full URL instead in the README? I.e. http://localhost:8666/@myMoijt/index

**Comment by selfcontained** [comment]
I think the concept of routes is pretty well known amongst deveopers, more-so than a magical full URL that mojito supports.  Developers are used to the concept of routing in their mvc, and to not mention it may make some assume that it only has these magical @MojitoName.action urls.  My 2cents.

**Comment by rwaldura** [comment]
bmharris: we're going to try to keep the README super lightweight, and have more solid documentation around routes in the Wiki etc. Thanks again for the patch though! Keep 'em coming!

**Comment by rwaldura** [comment]
E.g. http://developer.yahoo.com/cocktails/mojito/docs/code_exs/route_config.html

**Pull request closed without merging**
