### PR TITLE
Configurable Doctype - Based on User-Agent

### PR DESCRIPTION
**Pull request by gvaish**
Pull 121 (https://github.com/yahoo/mojito/pull/121) can be closed.

The updated version allows configurable DOCTYPE declaration based on User-Agent.

Actual code in commit #80bd20c4
(https://github.com/gvaish/mojito/commit/80bd20c4fb3997398991a4b0c0459aed71342175)

### CODE REVIEW

**Comment by gvaish** [comment]
Case study added in commit #a8cd0e2bb
(https://github.com/gvaish/mojito/commit/a8cd0e2bb0320657653369a68cc36e799b949543)

**Comment by epuidokas** [comment]
Not sure what policies the Mojito team has, but I'd clean up that commit history and leave the version incrementing out of this pull request.

**Comment by gvaish** [comment]
Erik,

Sure. No need to carry forward the complete commit history! :)

**Comment by mojit0** [comment]
This is a reasonable extension, but our goal for HTMLFrameMojit is that it be more API driven than "automagic" and something you may often write on your own to optimize the needs of your application. For that reason we're suggesting you use this as your own variant rather than bringing this patch in as the baseline version.

**Comment by gvaish** [comment]
Well, an issue... Doctype remains non-configurable in that case.
There is no way during processing (read: controller execution) that the info about "DOCTYPE" can be provided to HTMLFrameMojit except from application.json

I would be eager to know about alternate, API driven mechanism for the same.

**Comment by add0n** [comment]
I think, as a general rule, that we're moving towards having API (i.e. a call into Mojito) for things such as this, since it's much more powerful and flexible.

**Comment by gvaish** [comment]
Gotcha!

**Comment by drewfish** [comment]
I think we should take a different approach.  I think that Mojito should make it easy for people to implement their own equivalent of HTMLFrameMoijt.

If you look at HTMLFrameMojit today, it is doing two things:  putting Mojito client in the page, and putting other assets in the page.  That's it -- those are the only things that HTMLFrameMojit is doing that has anything to do with the Mojito framework.  Any special logic beyond that is specific to each application, and should be done in the application code, not in Mojito.

Of the two Mojito-specific things that HTMLFrameMojit does, deploying the client into the page is already pretty straightforward.  (It's a single call to ac.deploy, guarded by a check on the "deploy" flag in the config.)  That means Mojito just needs to provide an easy way to put the assets in the page.  (I think a clean approach to doing this would be to take that current logic from the HTMLFrameMojit controller and move it into the "assets" AC addon, probably into a method called renderAsHTML(location) or something like that.)

**Comment by gvaish** [comment]
Andrew,

Points noted. Infact, as I write this comment, I have some ideas running at the back of my mind... let me try to "revamp" the HTMLFrameMojit to "externalize" the reusable code into another component that can be used from elsewhere as well not just HTMLFrameMojit

**Pull request closed without merging**
