### PR TITLE
Revert "Merge pull request #1084 from caridy/yui-3-10-0"

### PR DESCRIPTION
**Pull request by lzhan**
This reverts commit b6c0b8c1d612f4b65ad4e5f974eaa10ec1215e72, reversing
changes made to 3ba3dd140eff64535e112bbb220cf7018c59a531.

### CODE REVIEW

**Comment by caridy** [comment]
Let's hold on this until I finish the investigation on 3.10.0 today!

**Comment by drewfish** [comment]
+1

**Comment by caridy** [comment]
@lzhan can you merge this?

**Comment by lzhan** [comment]
Yes, I am trying to solve a conflict and will merge this pr.

**Pull request merged**
