### PR TITLE
Allow user-provided middlewares with a name starting with 'mojito-' to gain access to the resource store, YUI instance, logger, context, etc.

### PR DESCRIPTION
**Pull request by jlecomte**

### CODE REVIEW

**Comment by drewfish** [comment]
+1

**Comment by mridgway** [comment]
+1 for the short term. In the long run, I think it makes sense not to differentiate between built-in and user-created middleware.

**Comment by isao** [comment]
Thanks Julien.

We'll get some guidelines up on the github wiki very soon, but we land all
new code on develop, not the master branch FYI.

I'll need to pull this to my develop, test and redo the pull request (or
you can if you have time).

Best,

Isao

-----Original Message-----
From: Julien Lecomte
<reply+i-4917852-2b1ee3f58f20405b6ab158e8a07b51588421d046-46951@reply.githu
b.com>
To: Isao Yagi isao@yahoo-inc.com
Subject: [mojito] Allow user-provided middlewares with a name starting
with 'mojito-' to gain access to the resource store, YUI instance, logger,
context, etc. (#187)

You can merge this Pull Request by running:

  git pull https://github.com/jlecomte/mojito master

Or you can view, comment on it, or merge it online at:

  https://github.com/yahoo/mojito/pull/187

-- Commit Summary --
- Allow user-provided middlewares with a name starting with 'mojito-' to
  gain access to the resource store, YUI instance, logger, context, etc.

-- File Changes --

M source/lib/index.js (14)

-- Patch Links --

  https://github.com/yahoo/mojito/pull/187.patch
  https://github.com/yahoo/mojito/pull/187.diff

---

Reply to this email directly or view it on GitHub:
https://github.com/yahoo/mojito/pull/187

**Comment by jlecomte** [comment]
Hey Isao, I'd appreciate if you could do it. I had originally checked out the develop branch but it wasn't stable at that time so I could not test my change. Let me know if I can help in any other way. Thanks!

**Comment by isao** [comment]
Yup no problem, thx

On Jun 6, 2012, at 5:01 PM, "Julien Lecomte" reply@reply.github.com wrote:

Hey Isao, I'd appreciate if you could do it. I had originally checked out the develop branch but it wasn't stable at that time so I could not test my change. Let me know if I can help in any other way. Thanks!

---

**Comment by isao** [comment]
Hi Julien,

I applied this patch off the develop branch in [my fork](https://github.com/isao/mojito/tree/usr-mw-develop), but our regressions fail. I also pushed this on a [branch named 0.3.26-pull187](https://github.com/yahoo/mojito/tree/0.3.26-pull187), which is applied to the last stable release. But.. our automated tests are now only working for code committed since then.

Is this tested and working in your dev/test env?

Isao

**Comment by jlecomte** [comment]
Hi Isao,

Yup, I am using it on my dev box, no problem at all! Something must have gone wrong during the merge.

**Comment by isao** [comment]
PIBCAK, my bad :)

it's back in the testing queue.

-----Original Message-----
From: Julien Lecomte
<reply+i-4917852-2b1ee3f58f20405b6ab158e8a07b51588421d046-46951@reply.githu
b.com>
To: Isao Yagi isao@yahoo-inc.com
Subject: Re: [mojito] Allow user-provided middlewares with a name starting
with 'mojito-' to gain access to the resource store, YUI instance, logger,
context, etc. (#187)

Hi Isao,

Yup, I am using it on my dev box, no problem at all! Something must have
gone wrong during the merge.

---

**Comment by isao** [comment]
passed regressions. hopefully before too long these wil be runnable by everyone.. :)

**Comment by isao** [comment]
Hi Julien,

Forgot to mention, it passed and I landed it on github in three places...
1. develop - to be included in the next release
2. master - by mistake
3. branch 0.3.26-pull187 - so you could use it in case there were
   regressions

Note 2 & 3 are essentially the same thing right now. But Fri we'll roll
0.3.27 onto master, which will swap YUI 3.4.x with 3.5.1.

This may create break your code. Fixups were required to our test cases as
part of the upgrade, I believe.

Which brings me to #3. For your release, you could of course just use the
patched version you're already using, or specify this in your app
package.json for some interim period:

```
"dependencies": {
   "mojito": "git://github.com/yahoo/mojito.git#0.3.26-pull187"
}
```

Isao

https://github.com/yahoo/mojito/tree/0.3.26-pull187

-----Original Message-----
From: Isao Yagi isao@yahoo-inc.com
To: Julien Lecomte 
<reply+i-4917852-2b1ee3f58f20405b6ab158e8a07b51588421d046-46951@reply.githu
b.com>
Subject: Re: [mojito] Allow user-provided middlewares with a name starting
with 'mojito-' to gain access to the resource store, YUI instance, logger,
context, etc. (#187)

PIBCAK, my bad :)

it's back in the testing queue.

-----Original Message-----
From: Julien Lecomte
<reply+i-4917852-2b1ee3f58f20405b6ab158e8a07b51588421d046-46951@reply.githu
b.com>
To: Isao Yagi isao@yahoo-inc.com
Subject: Re: [mojito] Allow user-provided middlewares with a name starting
with 'mojito-' to gain access to the resource store, YUI instance, logger,
context, etc. (#187)

Hi Isao,

Yup, I am using it on my dev box, no problem at all! Something must have
gone wrong during the merge.

---

**Pull request merged**
