### PR TITLE
update to Arrow devdep to ~0.0.77, descriptor update

### PR DESCRIPTION
**Pull request by isao**

### CODE REVIEW

**Comment by caridy** [comment]
If this is a re-run of a previous commit, make sure u also update some other new tests that are using the `../../../` trick.

**Comment by isao** [comment]
yes, it's a re-run, 6166f775ae4fef48adc21f5befa490ab18d2a803 is cherry-picked

looks like I need add'l commits anyway for travis to pick it up again.

**Comment by isao** [comment]
fyi travis is green for this on my build history https://travis-ci.org/isao/mojito/builds/7409900

**Comment by drewfish** [comment]
+1

(can't wait to upgrade to yui@3.10 also)

**Comment by lzhan** [comment]
Just found that arrow 0.0.77 reporting is changed. Everytime when new report is generated, old report file/dir is removed. There is a new option --keepTestReport, I am testing it to see if it works fine.

**Comment by lzhan** [comment]
--keepTestReport option works fine. Run.js need to be updated.

**Comment by lzhan** [comment]
+1

**Pull request merged**
