### PR TITLE
Fix issue #1306: ac.partial.render() throws error for handlebar custom helper

### PR DESCRIPTION
**Pull request by lzhan**

### CODE REVIEW

**Comment by caridy** [comment]
@lzhan are u still working on this one?

**Comment by lzhan** [comment]
Not really. But I just noticed that I need to fix the travis failure. About the issue with "partials" as dir name, if we don't want to make any change, we might need to document it.

**Comment by caridy** [comment]
+1

**Comment by caridy** [comment]
this solves issue #1306

**Pull request merged**
