### PR TITLE
Make handlebars render mustache templates

### PR DESCRIPTION
**Pull request by mridgway**
The final step of getting rid of the buggy Mu view engine is to remove it all together. In order to provide backwards compatibility with those that don't rename their template files, I propose that Handlebars render all existing mu.html templates. This works because Handlebars is a superset and implementation of the Mustache specification.

This would most likely be a phase-in for removal of mu.html support out of the box.

All regression tests pass in mojito-github-fork/82. The lone error was an invalid mustache syntax that somehow worked in Mu even though it shouldn't have. This error was fixed in the 'hbdefault' pull request.

### CODE REVIEW

**Comment by mojit0** [comment]
+1

**Comment by jenny** [comment]
This is a good change that we'd like to merge in. However, 0.5 introduces a number of significant changes that need to be merged into this PR first.

**Comment by lzhan** [comment]
0.5 is out. I will try to merge this pr.

**Comment by lzhan** [comment]
As Ren suggested, will revisit this after post 0.5 work is done.

**Comment by caridy** [comment]
@lzhan, I will cover this as part of PR #842, no worries.

**Comment by lzhan** [comment]
Great. Thanks Caridy.

**Comment by rwaldura** [comment]
included in #842, closing

**Pull request closed without merging**
