### PR TITLE
Updates yui and yuitest dependencies

### PR DESCRIPTION
**Pull request by okuryu**
This change need for installing Mojito on FreeBSD. See also yui/yui3#134 and yui/yuitest#16. Please review this one.

### CODE REVIEW

**Comment by isao** [comment]
passes secondary tests. We should do: "yuitest": "~0.7.4", "yui": "~3.5.1", to pick up future patch level upgrades too.

**Comment by okuryu** [comment]
@isao Agreed. I would like to push that change with this request if you want to do something.

**Comment by isao** [comment]
sure, please do. thank you

**Comment by isao** [comment]
fyi, just push the edit to your okuryu/ fork's update-package-json branch and it will appear in this pull request

**Comment by okuryu** [comment]
Yeah, I know. Already pushed the change into my branch.

**Pull request merged**
