### PR TITLE
fold tests/cli into tests/unit

### PR DESCRIPTION
**Pull request by isao**
- rename descriptor params.lib to params["lib-DISABLED-BZ6046277"] to disable coverage where they currently interfere with the test's use of mockery
- mv descriptor files so they follow arrow convention
- fix merge conflicts

### CODE REVIEW

**Comment by lzhan** [comment]
Isao: would you please update run.js--remove any cli related? Thanks.
Other than this. +1.

**Comment by isao** [comment]
thanks. the travis/npm-test run passes omm, let's see what travis and jenkins say. I hope the simpler `run.js test -u --path unit` in edfe1b83b9ce1e3cfa0ba401a7e71ce835a82bbb addresses the test count discrepency you noticed.

**Comment by isao** [comment]
test count dropped. making groupings more consistent with the usage of arrow --driver

**Comment by caridy** [comment]
@isao this is breaking jenkins.

**Comment by isao** [comment]
ok, the "Cannot load a local file without arrow_server running" errors should be fixed with pull #943

**Pull request merged**
