### PR TITLE
contextualizing seed and groups->app settings

### PR DESCRIPTION
**Pull request by caridy**
- producing secure copies of each of them by making copies.
- discarding duplicated entries in seed for better integration with shaker.

### CODE REVIEW

**Comment by drewfish** [comment]
BTW, travis is passing even with failed tests.  Not sure if the failures are related to this PR though.

```
Failed Descriptor Path : /home/travis/builds/yahoo/mojito/tests/func/examples/developerguide/developerguide_descriptor.json
18455Total Number of Failed Tests : 2
18456--------------------------------------------
18457Failed Descriptor Path : /home/travis/builds/yahoo/mojito/tests/func/usecases/usecasestest_descriptor.json
18458Total Number of Failed Tests : 3
```

**Comment by caridy** [comment]
It sounds like the same 5 failures that @lzhan was reporting in develop-perf.

**Comment by drewfish** [comment]
Looks good, but needs at least 1 unit test to make sure that appConfig.yui.config.seed is honored.

**Comment by caridy** [comment]
Fair enough, let me add the test.

**Comment by drewfish** [comment]
+1

**Pull request merged**
