### PR TITLE
seed refactor

### PR DESCRIPTION
**Pull request by caridy**
Goals:
- Reduce the memory allocation when YUI core modules should not be served from local server (default configuration)
- Clear separation between YUI core modules and app-level modules (including synthetic modules)
- As part of the separation, the seed will have, at least, 2 files, YUI Core Seed + App Seed.
- Support for relative path when using mojito build command.

Changes:
- moving logic to generate seed files into yui rs addon from deploy ac addon.
- making root and base for yui and app group to correlate.
- introducing staticHandling->serveYUIFromLocal configuration to disable serving yui from local app by default to preserve memory.

Basically, this PR will allow users to switch to server YUI from local, including combo, but the default configuration will be to load it from CDN. If you want to force to use YUI from local for development, or to be able to build html5apps and hybrid apps, you can use this setting:

```
{
    "settings": [ "environment:development" ],
    "staticHandling": {
        "serveYUIFromLocal": true
    }
}
```

Keep in mind that when using `mojito build` command, the `combine` flag should be set to `false` under `yui.config` because combo is not available in stand alone apps.

Other changes in this PR:
- supporting html5app->forceRelativePaths for yui loader, making root and base to be relative when needed.
- making default config.json a yaml file to add proper comments about default configurations.

TODO: 
- Update docs

### CODE REVIEW

**Comment by caridy** [comment]
This is also suppose to fix issue #982.

**Comment by isao** [comment]
(redacted)

**Comment by caridy** [comment]
@isao can you elaborate more?

**Comment by isao** [comment]
@caridy made this [gist](https://gist.github.com/isao/5009030) to explain, before I saw the full context of the commit (I mistakenly thought you replaced the str.replace instead of adding a second one).

sorry, nm :) 

:+1:

**Comment by imalberto** [comment]
+1

**Pull request merged**
