### PR TITLE
wip assets addon unit test port

### PR DESCRIPTION
**Pull request by isao**

### CODE REVIEW

**Comment by mojit0** [comment]
Gotta work on those syncs :)

**Comment by isao** [comment]
this is off `git checkout -b arrowd17c56aa up/arrow` and cherry-picking 17c56aa... I'm surprised. But I think we can just squash this entire branch onto develop.

**Comment by mridgway** [comment]
This should be merged into the arrow branch instead of develop right?

**Comment by isao** [comment]
@mridgway ah. you're right. I think I did this on my phone. closing!

**Pull request closed without merging**
