### PR TITLE
Develop perf

### PR DESCRIPTION
**Pull request by bthaeler**
This code provides two things.
1. A framework for logging debugging and performance metrics data on a per request basis.
2. Some instrumentation of the core mojito code, using this api.

To use this results of this system you will also need the npm package, mojito-debug-view. This will be released separately.

### CODE REVIEW

**Comment by caridy** [comment]
This PR is very long and confusing, probably because there is a mix of old code with new code, and refactors in the middle, I will need more time to make sense of it.

I do have few questions already:
- How does this work on client side?
- How a `model` for example, can have access to debugger?
- How does this work with the current perf api? They clearly overlap, one of them have to be blended.

**Comment by bthaeler** [comment]
The intent is to eventual make this api work on both the client and server side. We should be able to get the Debug UI to merge both server side and client side results together. This is a feature we plan to work on next quarter.

To use the debugger in a model, one would need to pass down debugger to the getData methods in the model.

The code does work woth the current perf api. If you enable perf marks, prof.PerfMark will be an available debug flag. The results will appear in a water fall display.

**Comment by caridy** [comment]
@bthaeler let's have a quick meeting to talk about this PR. /cc @drewfish

**Comment by drewfish** [comment]
Hi @bthaeler,

The `develop-perf` branch just went away, and github auto-closed pull requests against it.  You'll have to redo this pull request against the `develop` branch.  Sorry about this.

Drew

**Pull request closed without merging**
