### PR TITLE
removed lang dependencies from binders.

### PR DESCRIPTION
**Pull request by diervo**
The langs are already dependencies of the controller so we dont need it
here. It's causing the langs to get deployed always to the client.

### CODE REVIEW

**Comment by caridy** [comment]
@drewfish can you comment on this?

**Comment by drewfish** [comment]
I agree with the idea, but the proposed code isn't quite right, since without calling `_setYUIDependencies()` calling `_precomputeYUIDependencies()` is wasted effort.

Whether we need to call `_precomputeYUIDependencies()` or not depends on whether we intend to keep support for `dependencyCalculations:precomputed`.

**Comment by diervo** [comment]
But still, whatever calculation we do, the langs are not dependencies of the binder but the controller right? We should only need to ship those when the controller gets deployed.

**Comment by drewfish** [comment]
Yes, I agree.  However, the code in this pull request isn't right.

**Comment by diervo** [comment]
Ok, anyway with the Caridy changes that may be refactored somewhere else. So just to raise the error!

**Pull request closed without merging**
