### PR TITLE
Upgrade to YUI 3.5

### PR DESCRIPTION
**Pull request by mridgway**
I'm not sure if this is still being worked on by someone else, but I'd like to open this up and see if we can get some traction with this. Maybe @davglass can chime in too.

So far all of the tests run, but they do not pass. Here are my test failures: https://gist.github.com/2785983

This pull request should be considered incomplete until we can get all tests to pass.

### CODE REVIEW

**Comment by isao** [comment]
This got pushed to the next sprint for me, but Dav did email me about it. 

Thanks a bunch for the pull request,

On May 24, 2012, at 10:38 PM, "Michael Ridgway" reply@reply.github.com wrote:

I'm not sure if this is still being worked on by someone else, but I'd like to open this up and see if we can get some traction with this. Maybe @davglass can chime in too.

So far all of the tests run, but they do not pass. Here are my test failures: https://gist.github.com/2785983

This pull request should be considered incomplete until we can get all tests to pass.

You can merge this Pull Request by running:

 git pull https://github.com/mridgway/mojito yui

Or you can view, comment on it, or merge it online at:

 https://github.com/yahoo/mojito/pull/163

-- Commit Summary --
- Attempted upgrade to YUI 3.5
- Changed YUI version to 3.5.1

-- File Changes --

M source/lib/index.js (10)
M source/lib/management/commands/compile.js (4)
M source/lib/management/commands/test.js (18)
M source/lib/store.server.js (10)
M source/package.json (3)

-- Patch Links --

 https://github.com/yahoo/mojito/pull/163.patch
 https://github.com/yahoo/mojito/pull/163.diff

---

Reply to this email directly or view it on GitHub:
https://github.com/yahoo/mojito/pull/163

**Comment by davglass** [comment]
I took a quick peek at this today (note, I know nothing about mojito)

https://github.com/davglass/mojito/tree/3.5.1

I have it down to only failing 6 tests when running in "ondemand" mode:
https://gist.github.com/2788649

I didn't have time to dive into what "precomuting" mojito is doing under the hood with Loader, but it's not working properly. All of the errors that I saw before flipping that bit was due to it not loading any YUI modules. Switching over to "ondemand" forced it to use my Loader in Node and YUI core modules began loading again.

There were some serious updates (and shortcuts) added to 3.5.x's Loader that you guys should probably use. But I didn't have time to deep dive into the precomputed stuff to see if I could find it.

I'd be happy to "tag-team" this with one of you guys if you have time to explain how you guys are "precomputing" dependencies and then I can help you migrate to the newer Loader API's (which are much nicer) and get this finished.

**Comment by isao** [comment]
not sure, maybe store.server.js _sortYUIModules().. I'll dig in after my battle with jenkins.

**Comment by davglass** [comment]
Down to one failing now with my latest checkin:

```
FAILURE DETAILS:
================
mojito-store-server-tests :: Store tests :: appConfig deferAllOptionalAutoloads
breg
Expected: undefined (undefined)
Actual: /static/mojito/autoload/transport/beanregistry/registry.client-optional.js (string)


Total tests: 331    ✔ Passed: 309 ⚑ Deferred: 21    ✖ Failed: 1   93% pass rate
```

**Pull request closed without merging**
