### PR TITLE
fix mojito create -p option

### PR DESCRIPTION
**Pull request by isao**
- add port: "{{port}}" to application.json
- rename with .hb extension

### CODE REVIEW

**Comment by caridy** [comment]
@isao we are transforming the port from a numeric value to a string, for some reason @drewfish change it to a numeric value, can you comment?

**Comment by isao** [comment]
it was a trade-off to allow the raw json.hb file to be linted and syntax highlighted

**Comment by isao** [comment]
note, this is not intended for pr6

**Comment by drewfish** [comment]
I changed the port numbers in `tests/func/applications/apps.json` which is a bit different.

**Comment by caridy** [comment]
+1 then

**Pull request merged**
