### PR TITLE
delinted

### PR DESCRIPTION
**Pull request by drewfish**

### CODE REVIEW

**Comment by drewfish** [comment]
travis build fails -after- `mojito jslint` succeeds

**Comment by caridy** [comment]
deja-vu, I think I reviewed this commit few days ago. Anyway:
- why are we using "stupid" flag?
- Y.mojito.util.shouldShareYUIInstance(opts.appShareYUIInstance, this.instance); is either not needed or should be assigned to something I believe.

Still:

+1

**Comment by drewfish** [comment]
Yeah, this is a redo of PR #509.

**Comment by drewfish** [comment]
Without `/*stupid:true*/` I get `Unexpected sync method` errors.

**Pull request merged**
