### PR TITLE
Bug fixes in simple examples replacing "mojit_guid" with "mojit_view_id"

### PR DESCRIPTION
**Pull request by ricallinson**

### CODE REVIEW

**Comment by isao** [comment]
good catch
+1

**Comment by isao** [comment]
test and lint errors coming from your perf branch. these need to be applied to/from yahoo/develop

**Comment by drewfish** [comment]
I'm going to merge onto search-perf, since it's needed there too.

**Comment by isao** [comment]
ok, but it has nothing to do w/ perf (they're basically non-functional changes), and that branch won't hit develop for a while..

**Comment by caridy** [comment]
@isao I still see a bunch of them on `tests/fixtures/` when doing a grep.

**Pull request merged**
