### PR TITLE
PR #269 Added compatibility with Y.Model

### PR DESCRIPTION
**Pull request by drewfish**
This is PR #269 updated with a test and delinted.

### CODE REVIEW

**Comment by drewfish** [comment]
As mentioned in the original PR, this is related to bug #259.

**Comment by mridgway** [comment]
From what I understand, this patch makes a Y.Model available in a controller so that you could instantiate one or more instances of it. These models would then be passed to the view to be rendered. But the view does not have a way of access the attributes of the model because it should be using model.get('foo').

I think we need to discuss more in depth what integrating YAF components means for Mojito. We should come up with some functional use cases of how we would use the YAF components and work from there, instead of throwing the components in and sorting them out afterwards.

**Comment by caridy** [comment]
@mridgway until we get a better integration, the idea is to do something like this:

```
index: function(ac) {
    var foo = new ac.models.ModelFoo({/* model config */});
    foo.load(function() {
        ac.done(foo.toJSON());
    });
}
```

Although, I don't see the point of having the models collection, I rather prefer to do something like:

```
index: function(ac) {
    var foo = new Y.ModelFoo({/* model config */});
    foo.load(function() {
        ac.done(foo.toJSON());
    });
}
```

and defining the proper requirement as part of the controller's requires config, since that's more natural for YUI users, and ultimately, the optimization of what needs to be loaded (in the client side) in case you have more than one model under a mojit.

and eventually, once we get better integration with Y.View/Y.Renderer we should be able to do something more advanced, in this case passing the reference of the model into the view/renderer, just like YAF.

/cc @drewfish

**Comment by drewfish** [comment]
@mridgway I think you have a very good point.  We should have a complete answer for the integration before we take any steps (so that we take the right steps).

The assumption is that Y.Models are also useful for the controller.  However, that's very much from the "classic mojito" point of view, and doesn't take into account things like you've mentioned.

**Comment by mridgway** [comment]
I agree having the `ac.models` collection doesn't seem necessary.

This implementation at least gets users started with Y.Model, so I suppose that's a good thing. In the future if it's just a matter of changing `ac.done(model.toJSON())` to `ac.done(model)` then we're making progress towards our goal (which I think we should still have a solid plan for).

**Comment by drewfish** [comment]
Closing this, since the plan is to merge this work into the yaf-develop branch, which is PR #370.

**Pull request closed without merging**
