### PR TITLE
[YAF] view to template

### PR DESCRIPTION
**Pull request by drewfish**

### CODE REVIEW

**Comment by mridgway** [comment]
Yowza! +1 conceptually. Not sure if I can read through all of the changes though =P

**Comment by drewfish** [comment]
Yeah, 646 files changed :smile:, which makes me wonder how many files left _haven't_ changed.

**Comment by drewfish** [comment]
The unit tests (both kinds) pass when I run them by hand.  Haven't figured out how to run the functional tests yet though.

**Comment by rwaldura** [comment]
let's complete this when we really have some level of integration with YAF

**Pull request closed without merging**
