### PR TITLE
make test configs match internal for unit tests

### PR DESCRIPTION
**Pull request by isao**
functional tests are now excluded from travis-ci

### CODE REVIEW

**Comment by caridy** [comment]
+1

**Comment by isao** [comment]
tests failed so I'm applying the patch to increase the delay.. waiting for travis now.. https://travis-ci.org/isao/mojito/builds/4994538

**Comment by isao** [comment]
I rebased, so the orig test results for the failed commit (head of develop at the time with func tests enabled) doesn't appear above, but it is here https://travis-ci.org/isao/mojito/builds/4993672 fyi

**Comment by isao** [comment]
7 vs 9 failures

**Pull request merged**
