### PR TITLE
FIX mojito-mu and output-adapter-addon tests

### PR DESCRIPTION
**Pull request by imalberto**

### CODE REVIEW

**Comment by isao** [comment]
this would be great on develop as well

**Comment by caridy** [comment]
Do we really need app->config in there? That one is not longer set by default, instead ac.config.getAppConfig() is provided by mojito-config-addon. I think output adapter does not use that config anymore. Otherwise:

+1

**Comment by drewfish** [comment]
+1

**Comment by imalberto** [comment]
@caridy Constructor for action-context still set the app.config object. Can the config addon be accessed from the output-adapter addon ?

**Pull request merged**
